PROCESS BEFORE OUTPUT.

MODULE %_INIT_PBO.

MODULE %_PBO_REPORT.

MODULE %_PF_STATUS.

MODULE %_SO_CARR.

MODULE %_SO_CONN.

MODULE %_END_OF_PBO.

PROCESS AFTER INPUT.

  MODULE %_BACK AT EXIT-COMMAND.

  MODULE %_INIT_PAI.

CHAIN.
  FIELD  SO_CARR-LOW.
  FIELD  SO_CARR-HIGH.
  MODULE %_SO_CARR.
ENDCHAIN.

CHAIN.
  FIELD  SO_CONN-LOW.
  FIELD  SO_CONN-HIGH.
  MODULE %_SO_CONN.
ENDCHAIN.


CHAIN.
  FIELD  SO_CARR-LOW.
  FIELD  SO_CARR-HIGH.
  FIELD  SO_CONN-LOW.
  FIELD  SO_CONN-HIGH.
    MODULE %_BLOCK_1000000.
ENDCHAIN.

FIELD !PA_LV MODULE %_PA_LV .

CHAIN.
  FIELD  SO_CARR-LOW.
  FIELD  SO_CARR-HIGH.
  FIELD  SO_CONN-LOW.
  FIELD  SO_CONN-HIGH.
  FIELD PA_LV .
  MODULE %_END_OF_SCREEN.
  MODULE %_OK_CODE_1000.
ENDCHAIN.